# Project Name
TARGET = ex_scrubby

# Sources
CPP_SOURCES = scrubby.cpp pan.cpp buffer.cpp voice.cpp

# Library Locations
LIBDAISY_DIR = ../../../libdaisy
DAISYSP_DIR = ../../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

